services:
  postgres:
    image: postgres:17
    container_name: siembra_valores
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Siembra123
      POSTGRES_DB: siembravalores
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./api/schema.sql:/docker-entrypoint-initdb.d/schema.sql
volumes:
  postgres_data:
